// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaaxDQIKKHg10q14q-Buorvm0-QyRNUQ',
    appId: '1:659879338452:web:d4f302fd77319aa97ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    authDomain: 'sandesh-5fcac.firebaseapp.com',
    storageBucket: 'sandesh-5fcac.appspot.com',
    measurementId: 'G-32MZ3CJZBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByMJ12hsnwZzFeKFXU3DhmaeI_-1g42IE',
    appId: '1:659879338452:android:7fab73561400c8607ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    storageBucket: 'sandesh-5fcac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fyVnfX2RBRDKjOXHbLQvBcDh2s4NTSc',
    appId: '1:659879338452:ios:3b9d7c79f1f3d5a67ab641',
    messagingSenderId: '659879338452',
    projectId: 'sandesh-5fcac',
    storageBucket: 'sandesh-5fcac.appspot.com',
    androidClientId: '659879338452-bmntt70lh9liteckmpd52diuldb2mud2.apps.googleusercontent.com',
    iosClientId: '659879338452-ij1g7cq2l6jl7l5bf9mf2ujsock11scu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mySkenu',
  );

}