// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgz98ar2Dh14La2gdXe5rFLk2i6bHqwGk',
    appId: '1:73112150455:web:9a728baf47d402c3638832',
    messagingSenderId: '73112150455',
    projectId: 'my-skenu',
    authDomain: 'my-skenu.firebaseapp.com',
    storageBucket: 'my-skenu.appspot.com',
    measurementId: 'G-6JSF7NCEKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI6LpySzrLIPEEZaIHfXaEEt20pvjk0Yc',
    appId: '1:73112150455:android:8aa5bc6fa6ae2676638832',
    messagingSenderId: '73112150455',
    projectId: 'my-skenu',
    storageBucket: 'my-skenu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi5qtSQlL-EL7T8Brn6BC8HBelyVt1mJQ',
    appId: '1:73112150455:ios:7c640adfe6bef461638832',
    messagingSenderId: '73112150455',
    projectId: 'my-skenu',
    storageBucket: 'my-skenu.appspot.com',
    iosBundleId: 'com.example.mySkenu',
  );
}
